// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4dXH4ZGeup5e7dTr7clYPdbbGOLlV3ic',
    appId: '1:40857916915:web:3ca5ea0e5885fd67b7ee86',
    messagingSenderId: '40857916915',
    projectId: 'krang-27343',
    authDomain: 'krang-27343.firebaseapp.com',
    storageBucket: 'krang-27343.firebasestorage.app',
    measurementId: 'G-MSQPVVHLQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRfDcEqlNbUWje_s7yba9R_cVrT4f5ok',
    appId: '1:40857916915:android:74edda9274ea014fb7ee86',
    messagingSenderId: '40857916915',
    projectId: 'krang-27343',
    storageBucket: 'krang-27343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwIwq7EVI9f6nlL4M4idZ_JMZZ60dIwr4',
    appId: '1:40857916915:ios:1fd62ec39a763661b7ee86',
    messagingSenderId: '40857916915',
    projectId: 'krang-27343',
    storageBucket: 'krang-27343.firebasestorage.app',
    iosBundleId: 'com.example.krang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwIwq7EVI9f6nlL4M4idZ_JMZZ60dIwr4',
    appId: '1:40857916915:ios:1fd62ec39a763661b7ee86',
    messagingSenderId: '40857916915',
    projectId: 'krang-27343',
    storageBucket: 'krang-27343.firebasestorage.app',
    iosBundleId: 'com.example.krang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4dXH4ZGeup5e7dTr7clYPdbbGOLlV3ic',
    appId: '1:40857916915:web:2bb791b12d5bbf95b7ee86',
    messagingSenderId: '40857916915',
    projectId: 'krang-27343',
    authDomain: 'krang-27343.firebaseapp.com',
    storageBucket: 'krang-27343.firebasestorage.app',
    measurementId: 'G-2EJVC8BRZW',
  );
}
